### ISSUE TITLE
Script Pagination

### ISSUE THREAD

**Issue by defucilis** [defucilis/ScriptAxis#15]
This is a whole thing, but obviously I can't just dump the entire database whenever a user goes to the scripts page. I mean, I probably can for a little while until there are lots of scripts, but eventually it's going to become a problem.

So I need to figure out how to do pagination and implement the necessary UI to support it.

**Comment by MartinWeee** [comment]
A very important point. In my script database are already 1226 Scripts and thats only IRL scripts. And I am not at the end of script research on realtouchscripts.

**Comment by defucilis** [comment]
OK so this is done in commit 2a236bad, but there's one major issue.

The Prisma devs don't support filtering lists. i.e. if each Script has a list of Tags, and I say "here is a tag", there's currently no way for Prisma to return all the scripts that have that tag in their tag list.

Before this was a minor problem in that I was having to ignore tags when querying the database, and filtering the returned scripts on the server manually before returning it to the client. But now it's an even bigger problem because pagination requires me to count how many scripts would be returned from the query in total, and that count doesn't take into account applied "include" or "exclude" tags.

So basically, pagination is quite weird and buggy when the user has applied "include" or "exclude" tags (or talent filters, since they are also lists on the database)

Apparently this feature is coming early next year, so I think I'm just going to let it be a little weird for now and once they add the feature in, I'll fix pagination.

What this looks like for a user is that sometimes there'll be multiple pages, and each page will have fewer than 18 scripts in it. Or sometimes the UI will indicate that there are more pages than there actually are, and when the user navigates to one of the later pages, the UI goes "hey there aren't any scripts here". It's theoretically possible for there to be a situation where page 2 has no scripts, but page 3 does have scripts!
