### ISSUE TITLE
Better overview for the script pages

### ISSUE THREAD

**Issue by Slibowitz** [defucilis/ScriptAxis#32]
Hello.

I think the current script page is a bit confusing and could use more clarity and a better overview. So I created one with paint. Sorry it's only paint and you have to look at my bad paint skill, but it's the only tool I got and the only tool I know how to use. 

![Site new](https://user-images.githubusercontent.com/77641504/110256536-ba76be00-7f99-11eb-82fb-2976326be5a0.png)

This layout is inspired from the standard video platforms and also from the layout I use to make for my threads at eroscripts. 
Let me know what you think about it.

Also, I hope I did this correct here. It's the first time I am using github like this. 

Thanks in advance.
Slibowitz

**Comment by defucilis** [comment]
Hey that's a pretty valid UI wireframe, doesn't matter how you made it :D

That looks like a mobile layout

What do you think of the [example script page that mADsCRIPTS made](http://scriptaxis.wprojek.de/scripts/gym-clothes-and-huge-glass-dildo/)? Has many of the extra features.

One thing I don't think I'll do is add comments - I feel like EroScripts is already a great place to talk about scripts, and it introduces a huge amount of complexity if I need to add all the necessary features to avoid spam and whatnot. It would be possible to integrate EroScripts topic posts automatically into the page, but I'm not sure that really sits right with me, I want to be careful not to introduce competition to EroScripts.

**Comment by Slibowitz** [comment]
I just found out about this example madscripts has created. I really like that one. Great overview and a modern look. I wish I would have seen it earlier, otherwise I wouldn't have posted this I guess ^^

Only thing I would to have is the possibility to add my description. Either the same from eroscripts or a custom one. And I would like to see, that the creator gets a bit more highlighted. 

> I want to be careful not to introduce competition to EroScripts.

I didn't think about that point, and I do agree with your point. I think the discussion should be at eroscripts.

**Comment by defucilis** [comment]
There is description currently on all the pages - I add it by just copy-pasting the content of the EroScripts post :P

I'd definitely want to keep that in the new layout, probably it would go below the images and metadata, but above the 'related scripts' and whatnot area.

**Comment by Slibowitz** [comment]
> I'd definitely want to keep that in the new layout, probably it would go below the images and metadata, but above the 'related scripts' and whatnot area.

Great, thank you!
You can delete this issue if you want. I didn't see, that there is already a way better layout from madscripts. I should have checked the other issues before. Github is still a bit new and a bit confusing sometimes, sorry.

**Comment by defucilis** [comment]
Haha all good, I'll go ahead and close it. No stress, that preview ended up coming out of a longer conversation called 'mobile CSS' so it's not exactly clear!

I'm just happy you even made this issue it's the first time someone else opened an issue on the repo c':
